"""Compare the new codebase with the original scripts and write ``validation/report.md``.

    python validation/run_validation.py
"""

from __future__ import annotations

import sys
import tempfile
import time
from pathlib import Path

import numpy as np

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from piperom.inputs import load_settings, load_system  # noqa: E402
from piperom.pushover import run_pushover  # noqa: E402
from piperom.sdof import derive_sdof  # noqa: E402
from validation.legacy import (ARCHETYPES, EQUIV_STATIC_EXAMPLE, LEGACY_L, archetype,  # noqa: E402
                               compare_pushover, extract_support_displacements, match_hand_typed,
                               run_legacy_equivalent_static)

OUT = Path(__file__).resolve().parent / "report.md"


def main() -> None:
    lines = ["# Validation of `piperom` against the original scripts", "",
             "Generated by `python validation/run_validation.py`. Paths of the original scripts are relative to "
             "`code implementation for paper/`.", ""]

    # ------------------------------------------------------------------ 1. pushover
    lines += ["## 1. Adaptive pseudo-pushover vs `Pushover2D/pushover_results_*.txt`", "",
              "New engine run on `inputs/archetypes/*.yaml` with default settings and the legacy "
              "longitudinal backbone (`validation/legacy_static_C-TPS-L.csv`). The reference files store "
              "values with 3 decimals; a value matches if the new result formatted with 3 decimals is identical.", "",
              "| Archetype | Values | Differing | Max abs. difference | Run time (s) |", "|---|---|---|---|---|"]
    results = {}
    for tag in ARCHETYPES:
        t = time.time()
        cmp = compare_pushover(tag)
        results[tag] = cmp["result"]
        lines.append(f"| {tag} | {cmp['n_cells']} | {cmp['n_diff']} | {cmp['max_abs_diff']:.2e} | "
                     f"{time.time() - t:.1f} |")
        print(f"pushover {tag}: {cmp['n_diff']} differing of {cmp['n_cells']}")

    # ------------------------------------------------------------------ 2. SDOF pipeline
    with tempfile.TemporaryDirectory() as tmp:
        ref = run_legacy_equivalent_static(Path(tmp))
    system = load_system(EQUIV_STATIC_EXAMPLE)
    system.trapezes["longitudinal"] = str(LEGACY_L)
    p = derive_sdof(system, load_settings(), float(ref["dc"]))
    shape_ref = extract_support_displacements(ref["d_norm"], ref["stiff_mask"], int(ref["nOrth"]))
    rel = lambda a, b: abs(a - b) / abs(b)  # noqa: E731
    lines += ["", "## 2. SDOF parameters vs `equivalent_static.py` + `NLTHA_SDOF.py`", "",
              f"`code_proposed_procedure/equivalent_static.py` run unchanged (Delta_c = {float(ref['dc']):g} mm); "
              "`derive_sdof` on `inputs/examples/equivalent_static_example.yaml` (braces given as `count: 4`).", "",
              "| Quantity | Original | New | Relative difference |", "|---|---|---|---|",
              f"| Gamma | {float(ref['Gamma']):.10f} | {p.gamma:.10f} | {rel(p.gamma, float(ref['Gamma'])):.1e} |",
              f"| Effective mass (t) | {float(ref['M_eff']):.10f} | {p.effective_mass:.10f} | "
              f"{rel(p.effective_mass, float(ref['M_eff'])):.1e} |",
              f"| u_SDOF (mm) | {float(ref['u_sdof']):.10f} | {p.u_sdof:.10f} | {rel(p.u_sdof, float(ref['u_sdof'])):.1e} |",
              f"| Support shape (max abs. diff.) | {np.round(shape_ref, 4).tolist()} | "
              f"{np.round(p.support_shape, 4).tolist()} | {np.abs(p.support_shape - shape_ref).max():.1e} |",
              f"| Brace mask | {ref['stiff_mask'].tolist()} | {system.resolve().brace_mask.tolist()} | |"]

    # ------------------------------------------------------------------ 3. hand-typed SDOF
    lines += ["", "## 3. Hand-typed constants in `Pushover_SDOF/*.py` (information only)", "",
              "For each archetype, the pushover step whose derived parameters best match the hand-typed Gamma and "
              "transverse-support shape (in either order). The original Delta_c used for each SDOF is not recorded "
              "in the repository. `max |dphi_T|` is the largest difference in the transverse-support shape.", "",
              "| Archetype | Best Delta_c (mm) | Gamma derived / typed | max \\|dphi_T\\| | M_eff derived / typed (t) "
              "| nT derived / typed | nL derived / typed | Note |",
              "|---|---|---|---|---|---|---|---|"]
    for tag in ARCHETYPES:
        m = match_hand_typed(tag, results[tag])
        h = m["hand"]
        if h["rigid"]:
            note = "typed SDOF is rigid-body (shape = 1) with 15 transverse braces, not derived from the 2D model"
        elif m["max_dphi_T"] < 0.01 and abs(m["gamma"] - h["gamma"]) < 0.01:
            note = "Gamma and shape match a pushover step"
        elif m["max_dphi_T"] < 0.01:
            note = "shape matches a pushover step, Gamma does not"
        else:
            note = "no step matches"
        if m["nL"] != h["nL"] and not h["rigid"]:
            note += f"; typed nL = {h['nL']} but the 2D model has {m['nL']} longitudinal trapezes"
        dphi = "n/a" if not np.isfinite(m["max_dphi_T"]) else f"{m['max_dphi_T']:.3f}"
        lines.append(f"| {tag} | {m['delta_c']:.2f} | {m['gamma']:.3f} / {h['gamma']} | {dphi} | "
                     f"{m['effective_mass']:.2f} / {h['mass']} | {m['nT']} / {h['nT']} | {m['nL']} / {h['nL']} | {note} |")

    # ------------------------------------------------------------------ 4. trapeze files
    lines += ["", "## 4. Effect of using the trapeze files as the single source", "",
              "The new code derives the static trilinear backbone from the Pinching4 files: the longitudinal "
              "point 3 becomes 10000 N at 24 mm (file) instead of 11500 N (original static code). "
              "Differences of the default run with respect to the legacy run:", "",
              "| Archetype | Max rel. change in base shear | Base shear at 50 mm, legacy / default (kN) "
              "| Gamma at 50 mm, legacy / default |", "|---|---|---|---|"]
    settings = load_settings()
    for tag in ARCHETYPES:
        new = run_pushover(archetype(tag, legacy_trapezes=False), settings)
        old = results[tag]
        vb_old = np.array([s.base_shear for s in old.steps])
        vb_new = np.array([s.base_shear for s in new.steps])
        lines.append(f"| {tag} | {np.max(np.abs(vb_new - vb_old) / np.abs(vb_old)):.1%} | "
                     f"{vb_old[-1] / 1e3:.1f} / {vb_new[-1] / 1e3:.1f} | "
                     f"{old.steps[-1].gamma:.3f} / {new.steps[-1].gamma:.3f} |")
        print(f"default trapezes {tag} done")

    OUT.write_text("\n".join(lines) + "\n")
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
