"""Compare the time-history engines with the paper's results and write ``validation/timehistory_report.md``.

* SDOF: the SDOFs typed into ``Pushover_SDOF/*.py`` under the first RECORDS records of ``S4_IM`` at IM1-IM10, against
  ``Results/<M>_peak_displacements.npy`` (columns = IM1-IM10, rows = records in ``Names.txt`` order).
* 3D: each 3D model at IM10 under the first ground motion in both orientations, against
  ``Results/<M>_biron_DispX.txt`` / ``DispY.txt`` (largest peak over the braced nodes; row = index of
  the record applied in that direction).

    python validation/run_timehistory_validation.py [--only sdof|3d] [--workers N]
"""

from __future__ import annotations

import argparse
import sys
import time
from concurrent.futures import ProcessPoolExecutor
from pathlib import Path

import numpy as np

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from validation.legacy import ARCHETYPES, PAPER, hand_typed_sdof_model  # noqa: E402

OUT = Path(__file__).resolve().parent / "timehistory_report.md"
LEVELS = range(1, 11)
RECORDS = 4          # first two ground motions (both components): a sample, to keep the run short


def sdof_case(tag: str) -> dict:
    from piperom.motions import motion_set
    from piperom.timehistory import TimeHistorySettings, run_sdof_time_history
    ms, s = motion_set("S4_IM"), TimeHistorySettings.from_dict()
    model = hand_typed_sdof_model(tag)
    records = ms.records[:RECORDS]
    new = np.array([[run_sdof_time_history(model, ms.load(r, lv), s).peak_u for lv in LEVELS] for r in records])
    ref = np.load(PAPER / "Results" / f"{tag[:3]}_peak_displacements.npy", allow_pickle=True).item()
    ref = ref["dispXs" if tag[3] == "x" else "dispYs"][:RECORDS]
    rel = np.abs(new - ref) / np.abs(ref)
    return {"tag": tag, "n": rel.size, "median": float(np.median(rel)), "p99": float(np.percentile(rel, 99)),
            "max": float(rel.max()), "n_over_1pct": int((rel > 0.01).sum())}


def model3d_case(args) -> dict:
    name, rot = args
    from piperom.motions import motion_set
    from piperom.verification3d import Verification3DSettings, braced_peaks, load_model3d, run_3d
    ms, m = motion_set("S4_IM"), load_model3d(name)
    a, b = ms.pairs()[0]
    rx, ry = (a, b) if rot == 0 else (b, a)
    t = time.time()
    r = run_3d(m, ms.load(rx, 10), ms.load(ry, 10), Verification3DSettings.from_dict())
    out = {"model": name, "x": rx, "y": ry, "completed": r.completed, "seconds": time.time() - t}
    R = PAPER / "Results"
    for d, peak in braced_peaks(m, r).items():
        row = ms.records.index(rx if d == "x" else ry)
        ref = np.loadtxt(R / f"{name}_biron_Disp{d.upper()}.txt")[row, 9]
        out[f"new_{d}"], out[f"ref_{d}"] = peak, float(ref)
    return out


SECTIONS = {"sdof": OUT.with_name(".timehistory_sdof.md"), "3d": OUT.with_name(".timehistory_3d.md")}


def sdof_section(workers: int) -> str:
    lines = ["## SDOF time history (`piperom.timehistory`)", "",
             f"SDOF definitions typed into `Pushover_SDOF/*.py` (mass and springs as in the scripts), the first "
             f"{RECORDS} records of `S4_IM` × IM1–IM10, compared with `Results/<M>_peak_displacements.npy`.", "",
             "| SDOF | Values | Median rel. diff. | 99th percentile | Max | Values > 1% |", "|---|---|---|---|---|---|"]
    with ProcessPoolExecutor(workers) as pool:
        for c in pool.map(sdof_case, ARCHETYPES):
            print("sdof", c, flush=True)
            lines.append(f"| {c['tag']} | {c['n']} | {c['median']:.1e} | {c['p99']:.1e} | {c['max']:.1e} | "
                         f"{c['n_over_1pct']} |")
    return "\n".join(lines)


def model3d_section(workers: int) -> str:
    lines = ["## 3D verification (`piperom.verification3d`)", "",
             "Each model at IM10 under the first ground motion in both orientations, with the default settings "
             "(convergence test `EnergyIncr`), compared with `Results/<M>_biron_DispX/Y.txt`: largest peak "
             "displacement over the braced nodes.", "",
             "| Model | x / y records | Completed | x: new / paper (mm) | y: new / paper (mm) | Run time (s) |",
             "|---|---|---|---|---|---|"]
    cases = [(m, rot) for m in sorted({t[:3] for t in ARCHETYPES}) for rot in (0, 1)]
    with ProcessPoolExecutor(workers) as pool:
        for c in pool.map(model3d_case, cases):
            print("3d", c, flush=True)
            lines.append(f"| {c['model']} | {c['x']} / {c['y']} | {c['completed']} | "
                         f"{c['new_x']:.3f} / {c['ref_x']:.3f} | {c['new_y']:.3f} / {c['ref_y']:.3f} | "
                         f"{c['seconds']:.0f} |")
    return "\n".join(lines)


def write_report() -> None:
    parts = ["# Validation of the time-history engines against the paper's results", "",
             "Generated by `python validation/run_timehistory_validation.py`."]
    for key, path in SECTIONS.items():
        parts += ["", path.read_text() if path.exists() else f"## {key}: not run yet"]
    OUT.write_text("\n".join(parts) + "\n")
    print(f"wrote {OUT}")


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--only", choices=["sdof", "3d"], help="run one part (the other keeps its last result)")
    ap.add_argument("--workers", type=int, default=8)
    args = ap.parse_args()
    for key, fn in (("sdof", sdof_section), ("3d", model3d_section)):
        if args.only in (None, key):
            SECTIONS[key].write_text(fn(args.workers))
            write_report()


if __name__ == "__main__":
    main()
